```{r}
require(tcltk)
require(tcltk2)

tt <- tktoplevel()
label.widget <- tklabel(tt, text = "Hello, World!")
button.widget <- tkbutton(tt, text = "Push",
                          command = function()cat("OW!\n"))
tkpack(label.widget, button.widget) # geometry manager
# see Tk-commands
```
```{r}
tkdestroy(tt)


## test for themed widgets
if(as.character(tcl("info", "tclversion")) >= "8.5") {
    # make use of themed widgets
    # list themes
    as.character(tcl("ttk::style", "theme", "names"))
    # select a theme -- here pre-XP windows
    tcl("ttk::style", "theme", "use", "winnative")
} else {
    # use Tk 8.0 widgets
}
```
============================================================================= 

```{r}
require(tcltk)
mydialog <- function(){

    xvar <- tclVar("")
    yvar <- tclVar("")
    zvar <- tclVar("")
    
    tt <- tktoplevel()
    
    tkwm.title(tt,"MYTEST")
    
    x.entry <- tkentry(tt, textvariable=xvar)
    y.entry <- tkentry(tt, textvariable=yvar)
    z.entry <- tkentry(tt, textvariable=zvar)
    
    reset <- function() {
    tclvalue(xvar)<-""
    tclvalue(yvar)<-""
    tclvalue(zvar)<-""
}

reset.but <- tkbutton(tt, text="Reset", command=reset)

submit <- function() {
    x <- as.numeric(tclvalue(xvar))
    y <- as.numeric(tclvalue(yvar))
    z <- as.numeric(tclvalue(zvar))
    tkmessageBox(message=paste("x + y + z = ", x+y+z, ""))
}

submit.but <- tkbutton(tt, text="submit", command=submit)

quit.but <- tkbutton(tt,
                     text = "Close Session", 
                     command = function() {
                         q(save = "no")
                         tkdestroy(tt)
                         }
                     )

tkgrid(tklabel(tt,text="Put your variables.."),columnspan=3, pady = 10)
tkgrid(tklabel(tt,text="x variable"), x.entry, pady= 10, padx= 10)
tkgrid(tklabel(tt,text="y variable"), y.entry, pady= 10, padx= 10)
tkgrid(tklabel(tt,text="z variable"), z.entry, pady= 10, padx= 10)
tkgrid(submit.but, reset.but, quit.but, pady= 10, padx= 10)

}

mydialog()
```
